site_name: "Mathias Obsidian Vault"
site_description: "Min personlige videnbase med C# noter, projekter og dokumentation"
site_author: "Mathias"
site_url: "https://docs.mags.dk"


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - "C# Bogen":
    - "CSharp-Bogen/0. Oversigt.md"
    - "CSharp-Bogen/1. Dit første program.md"
    - "CSharp-Bogen/2. Variabler.md"
    - "CSharp-Bogen/3. Expressions og operatører.md"
    - "CSharp-Bogen/4. Inputs.md"
    - "CSharp-Bogen/5. Control Flow.md"
    - "CSharp-Bogen/6. Klasser og Objekter.md"
    - "CSharp-Bogen/7. Loops og iterationer.md"
    - "CSharp-Bogen/8. Metoder - Funktioner.md"
    - "CSharp-Bogen/9. Debugging.md"
    - "CSharp-Bogen/10. Kodestandarter.md"
  - Kurser:
    - "GF1": "GF1/Oversigt.md"
    - "H1": "H1/Oversigt.md"
    - "H2": "H2/Oversigt.md"
    - "H3": "H3/Oversigt.md"
    - "H4": "H4/Oversigt.md"
    - "H5": "H5/Oversigt.md"
    - "H6": "H6/Oversigt.md"
  - Teknologier:
    - "Blazor": "Blazor/Oversigt.md"
    - "Web API": "Web API med CSharp/Oversigt.md"

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/mathias"
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/mathias"