version: '3.8'

services:
  videnstjek-blazor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8067
    ports:
      - "8067:8067"
    volumes:
      - ./Blazor:/src
      - /src/bin
      - /src/obj
    command: dotnet watch run --urls http://+:8067
