version: '3.8'
services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  flutterweb:
    build:
      context: ../flutter_app
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - flutterweb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
